# Compose file to spin up a local Snipe-IT for development.

services:
  snipeit:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    ports:
      - "8000:80"
    depends_on:
      redis:
        # The default needs to be stated.
        condition: service_started
      mariadb2:
        condition: service_healthy
        restart: true
    env_file:
      - .env.dev.docker

  mariadb2:
    image: mariadb:11.4.7
    volumes:
      - mariadb2:/var/lib/mysql
    env_file:
      - .env.dev.docker
    ports:
      - "3316:3306"
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#compose-file-example
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 2s
      retries: 5

  redis:
    image: redis:7.4.3

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

volumes:
  mariadb2: {}
